### ISSUE TITLE
Glad you are alive

### ISSUE THREAD

**Issue by moohyun69** [Nightshades1/MBII-CustomEdition#1]
I doubt you would remember me tho, but i was the guy from d3scene to your skype (when it was alive, sadly they wiped all tuts after updating forum) years ago. just want to say thank you for all of your works. based on your tuts i made interst and studied  software enginnering and reversing. i even still hacks HoTS and SC2 till today.

also congrats about D2 getting remastered. iirc u loved that game arentcha :D
stay safe at france!

with <3 from seoul

**Comment by Nightshades1** [comment]
> 
> 
> I doubt you would remember me tho, but i was the guy from d3scene to your skype (when it was alive, sadly they wiped all tuts after updating forum) years ago. just want to say thank you for all of your works. based on your tuts i made interst and studied software enginnering and reversing. i even still hacks HoTS and SC2 till today.
> 
> also congrats about D2 getting remastered. iirc u loved that game arentcha :D
> stay safe at france!
> 
> with <3 from seoul

Hey, Nice :hear_no_evil: :heart: Glad that you managed to practice and learn, on my side i've been constantly learning as well and i'm now at the point where i can write server emulator or do amazing shit on mobile game hacking and i pass, Heroes i gave up because i don't care but you could with some work bypass the anticheat and CRC check (search for all CRC32 processor opcodes) nasty blizzard using raw CPU instruction for AMD/INTEL "CRC32" and another one (i forgot the name) to instantly generate an exception (the instruction simply generate a test crash XD)

You can still load your own custom map instead of the one legit (in vs AI), i remember i had my own map with auto win, i think i was level 3000 with 3200 chests :joy: 

Lol nice to see you again, and my skype, i quite gave up on it, i'm on discord now :joy:

**Comment by moohyun69** [comment]
exactly! cool shit is you can play custom map on hots if both side loads swapped map xD

if you dont mind, lmk your discord since its good to in touch with good h4xor with you :)

**Comment by Nightshades1** [comment]
My discord is Nightshades#0955 ;P
